#!/usr/bin/env bash
# desktop-icon.sh — install a one-click desktop launcher for the RRRs stack.
#
# WHAT IT BUILDS
#   Double-click the "RRRs Media VM" desktop icon:
#     1. starts the casaos-vm if it is not already running,
#     2. waits until the CasaOS web UI answers (up to ~3 min),
#     3. opens all 8 service web UIs as tabs in Firefox:
#        CasaOS 18000 / Prowlarr 19696 / Radarr 17878 / Sonarr 18989 /
#        Readarr 18787 / Lidarr 18686 / qBittorrent 18085 / SABnzbd 18080
#   The applications-menu entry also offers right-click actions:
#     "Start VM only"     — start + wait ready, no browser
#     "Open web UIs only" — browser tabs, stack must be up
#
# SUPPORTED HOSTS
#   Ubuntu 24.04 — tested on ailab (KDE Plasma X11 + GNOME-ready fallback);
#                  snap Firefox detected, plain `firefox` command is the same.
#   openSUSE Leap 15.6 — same standard .desktop + firefox mechanism (GNOME or KDE).
#
# USAGE
#   bash vm/desktop-icon.sh            # install / refresh (idempotent)
#   bash vm/desktop-icon.sh --remove   # uninstall
#
# INSTALLED FILES (all under $HOME; nothing system-level is touched)
#   ~/.local/bin/rrrs-vm-start                          — the launcher script
#   <Desktop>/rrrs-media-vm.desktop                     — the double-click icon
#   ~/.local/share/applications/rrrs-media-vm.desktop   — applications-menu copy
#
# NOTES
#   * LAN IP is resolved at CLICK time via vm/_machine.sh
#     (env RRR_* > machines/current/machine.env > autodetect), so the icon
#     follows the active machine set — no reinstall after select-machine.sh.
#   * Desktop trust: file is installed executable (KDE/Plasma: launches
#     directly). On GNOME/DING the installer also sets metadata::trusted; if
#     GNOME still asks, right-click the icon -> "Allow Launching" (once).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
. "$REPO/vm/_machine.sh"

LAUNCHER="$HOME/.local/bin/rrrs-vm-start"
APP_ID="rrrs-media-vm"
APPS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || echo "$HOME/Desktop")"

OS_ID="unknown"
[ -r /etc/os-release ] && . /etc/os-release && OS_ID="${ID:-unknown}"

pick_icon() {  # first icon name that actually exists on this machine
  local cand hit
  for cand in applications-multimedia video-display preferences-system-network utilities-terminal; do
    hit="$(find /usr/share/icons /var/lib/snapd/desktop/icons /usr/share/pixmaps \
           -name "${cand}.*" 2>/dev/null | head -n1 || true)"
    [ -n "$hit" ] && { echo "$cand"; return; }
  done
  echo utilities-terminal
}
ICON="$(pick_icon)"

if [ "${1:-}" = "--remove" ]; then
  rm -f "$LAUNCHER" "$APPS_DIR/$APP_ID.desktop" "$DESKTOP_DIR/$APP_ID.desktop"
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$APPS_DIR" || true
  echo "removed: $LAUNCHER"
  echo "removed: $APPS_DIR/$APP_ID.desktop"
  echo "removed: $DESKTOP_DIR/$APP_ID.desktop"
  exit 0
fi

mkdir -p "$(dirname "$LAUNCHER")" "$APPS_DIR" "$DESKTOP_DIR"

# ---- 1/2: the launcher (placeholder __REPO__ substituted below) ------------
cat > "$LAUNCHER" <<'LAUNCHER_EOF'
#!/usr/bin/env bash
# Generated by vm/desktop-icon.sh — do not edit; re-run the installer instead.
set -u
REPO="__REPO__"
. "$REPO/vm/_machine.sh"
note() { command -v notify-send >/dev/null 2>&1 && notify-send -a "RRRs VM" "$@" || true; }

IP="${RRR_LAN_IP:-}"
if [ -z "$IP" ]; then
  note "Cannot resolve LAN IP" "Run vm/select-machine.sh <set> in a terminal."
  exit 1
fi

MODE="${1:-all}"                    # all | start | tabs
PORTS=(18000 19696 17878 18989 18787 18686 18085 18080)
NAMES=(CasaOS Prowlarr Radarr Sonarr Readarr Lidarr qBittorrent SABnzbd)
URLS=()
for i in "${!PORTS[@]}"; do URLS+=("http://$IP:${PORTS[$i]}"); done

vm_running() { "$REPO/vm/vm-power.sh" status 2>/dev/null | grep -qi 'running'; }
wait_ready() {                      # CasaOS UI answers => whole stack is up
  local i
  for i in $(seq 1 60); do          # 60 x 3s = 3 min max
    curl -sf -o /dev/null --max-time 3 "http://$IP:18000" && return 0
    sleep 3
  done
  return 1
}
open_tabs() {
  local b c u
  for c in firefox firefox-esr; do
    command -v "$c" >/dev/null 2>&1 && { b="$c"; break; }
  done
  if [ -n "${b:-}" ]; then
    nohup "$b" "${URLS[@]}" >/dev/null 2>&1 &
  else                             # last resort: default browser, one tab at a time
    for u in "${URLS[@]}"; do nohup xdg-open "$u" >/dev/null 2>&1 & done
  fi
}

case "$MODE" in
  start)
    if vm_running; then note "VM already running" "CasaOS: http://$IP:18000"; exit 0; fi
    note "Starting casaos-VM…" "Web UIs ready in about a minute."
    "$REPO/vm/vm-power.sh" start \
      || { note "Failed to start VM" "Run in a terminal: bash vm/vm-power.sh start"; exit 1; }
    if wait_ready; then note "VM ready" "CasaOS: http://$IP:18000"
    else note "VM not ready after 3 min" "Check: bash vm/check-vm.sh"; exit 1; fi
    ;;
  tabs)
    vm_running || { note "VM is not running" "Double-click the icon for a full start."; exit 1; }
    wait_ready || { note "Stack not answering" "Check: bash vm/check-vm.sh"; exit 1; }
    note "Opening ${#URLS[@]} tabs" "${URLS[0]}"
    open_tabs
    ;;
  all)
    if ! vm_running; then
      note "Starting casaos-VM…" "The ${#URLS[@]} web UIs open automatically when ready."
      "$REPO/vm/vm-power.sh" start \
        || { note "Failed to start VM" "Run in a terminal: bash vm/vm-power.sh start"; exit 1; }
    fi
    if wait_ready; then
      note "RRRs stack ready" "Opening ${#URLS[@]} Firefox tabs"
      open_tabs
    else
      note "Timed out on http://$IP:18000" "Check: bash vm/check-vm.sh"; exit 1
    fi
    ;;
  *) echo "usage: ${0##*/} [all|start|tabs]" >&2; exit 2 ;;
esac
exit 0
LAUNCHER_EOF
sed -i "s|__REPO__|$REPO|" "$LAUNCHER"
chmod 755 "$LAUNCHER"

# ---- 2/2: the .desktop entry (icon + menu actions) -------------------------
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<'DESKTOP_EOF'
[Desktop Entry]
Type=Application
Version=1.0
Name=RRRs Media VM
Comment=Start VM if needed, then open all *arr web UIs as Firefox tabs
Exec=__LAUNCHER__
Icon=__ICON__
Terminal=false
Categories=Network;FileTransfer;
Keywords=casaos;radarr;sonarr;prowlarr;lidarr;readarr;qbittorrent;sabnzbd;vm;
Actions=start;tabs;

[Desktop Action start]
Name=Start VM only
Exec=__LAUNCHER__ start

[Desktop Action tabs]
Name=Open web UIs only
Exec=__LAUNCHER__ tabs
DESKTOP_EOF
sed -e "s|__LAUNCHER__|$LAUNCHER|g" -e "s|__ICON__|$ICON|g" \
    "$TMP" > "$APPS_DIR/$APP_ID.desktop"
cp "$APPS_DIR/$APP_ID.desktop" "$DESKTOP_DIR/$APP_ID.desktop"
chmod 755 "$APPS_DIR/$APP_ID.desktop" "$DESKTOP_DIR/$APP_ID.desktop"

# GNOME/DING needs an explicit trust flag before double-click launch; harmless elsewhere.
gio set "$DESKTOP_DIR/$APP_ID.desktop" metadata::trusted true 2>/dev/null || true
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$APPS_DIR" || true

echo "installed on $OS_ID (desktop: ${XDG_CURRENT_DESKTOP:-unknown}):"
echo "  icon      : $DESKTOP_DIR/$APP_ID.desktop  (Icon=$ICON)"
echo "  menu entry: $APPS_DIR/$APP_ID.desktop"
echo "  launcher  : $LAUNCHER"
echo "  LAN IP    : $RRR_LAN_IP  (resolved at click time; machine set '$MACHINE_SET')"
if ! command -v notify-send >/dev/null 2>&1; then
  case "$OS_ID" in
    opensuse*|suse*) echo "  hint: notifications need  ->  sudo zypper install libnotify-tools" ;;
    ubuntu|debian*)  echo "  hint: notifications need  ->  sudo apt install libnotify-bin" ;;
  esac
fi
echo
echo "Done. Double-click the icon to start the VM + open the 8 service tabs."
